swagger: "2.0"

info:
  title: Accountability Expense-Tracker API
  version: 1-oas3
  
host: accountability-190955e8b06f.herokuapp.com
basePath: /api
schemes:
  - https

paths:
  /login:
    post:
      summary: Application user login endpoint
      description: Performs user authentication
      parameters:
      - in: body
        name: Login
        schema:
              $ref: '#/definitions/LoginDefinition'
      responses:
        "200":
          description: Authentication successful
          schema:
              $ref: '#/definitions/UserFullRow'
        "400":
          description: Malformed request or JSON on front-end
          schema:
                $ref: '#/definitions/ErrorInfo'
        "404":
          description: "Authentication failure, either wrong username or password"
          schema:
                $ref: '#/definitions/ErrorInfo'
        "500":
          description: Unknown error or exception on back-end
          schema:
                $ref: '#/definitions/ErrorInfo'
  /registerUser:
    post:
      summary: New user registration endpoint
      description: Creates a new application user
      parameters:
      - in: body
        name: Register
        schema:
          $ref: '#/definitions/RegisterDefinition'
      responses:
        "200":
          description: Registration successful
          schema:
              $ref: '#/definitions/UserFullRow'
        "400":
          description: Malformed request or JSON on front-end
          schema:
              $ref: '#/definitions/ErrorInfo'
        "409":
          description: Email already exists
          schema:
              $ref: '#/definitions/ErrorInfo'
        "500":
          description: Unknown error or exception on back-end
          schema:
              $ref: '#/definitions/ErrorInfo'
  /trips/createTrip:
    post:
      summary: CREATE trip endpoint
      description: Create a new, empty trip
      parameters:
      - in: body
        name: JSON
        schema:
          type: object
          properties:
            leaderId:
              type: string
              description: ID of the user that owns the trip
            name:
              type: string
              description: Title of the trip
            notes:
              type: string
              description: Miscellaneous description for the trip
      responses:
        "200":
          description: OK
          schema:
            type: object
            properties:
              tripId:
                description: The ID of the created trip
        "400":
          description: Malformed request or JSON
          schema:
            $ref: '#/responses/BadRequest'
  /trips/readTrip:
    post:
      summary: READ trip endpoint
      description: Get a trip with its associated users and expenses
      parameters:
      - in: body
        name: JSON
        schema:
          type: object
          properties:
            tripId:
              type: string
              description: ID of the trip to read
      responses:
        "200":
          description: OK
          schema:
            type: object
            properties:
              leaderId:
                type: string
                description: ID of the user that owns the trip
              name:
                type: string
                description: Title of the trip
              notes:
                type: string
                description: Miscellaneous description for the trip 
              allMembers:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    email:
                      type: string
              allExpenses:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    name:
                      type: string
                    description:
                      type: string
                    cost:
                      type: number
        "400":
          description: Malformed request or JSON
          schema:
            $ref: '#/responses/BadRequest'
  /trips/updateTrip:
    post:
      summary: UPDATE trip endpoint
      description: Modify trip information
      parameters:
      - in: body
        name: JSON
        schema:
          type: object
          properties:
            tripId:
              type: string
              description: ID of the trip to modify
            name:
              type: string
              description: Title of the trip
            notes:
              type: string
              description: Miscellaneous description for the trip
      responses:
        "200":
          description: OK
          schema:
            type: object
            properties:
              tripId:
                description: Same as input ID
        "400":
          description: Malformed request or JSON
          schema:
            $ref: '#/responses/BadRequest'
  /trips/deleteTrip:
    post:
      summary: DELETE trip endpoint
      description: Remove a trip and associated data
      parameters:
      - in: body
        name: JSON
        schema:
          type: object
          properties:
            tripId:
              type: string
              description: ID of the trip to delete
      responses:
        "200":
          description: OK
        "400":
          description: Malformed request or JSON
          schema:
            $ref: '#/responses/BadRequest'
  /expenses/createExpense:
    post:
      summary: CREATE expense endpoint
      description: Create a new, blank expense
      parameters:
      - in: body
        name: JSON
        schema:
          type: object
          properties:
            tripId:
              type: string
              description: ID of the trip this expense will belong to
            name:
              type: string
            description:
              type: string
            cost:
              type: number
      responses:
        "200":
          description: OK
          schema:
            type: object
            properties:
              expenseId:
                description: ID of the newly created expense
                type: string
        "400":
          description: Malformed request or JSON
          schema:
            $ref: '#/responses/BadRequest'
  /expenses/readExpense:
    post:
      summary: READ expense endpoint
      description: Read information about an expense
      parameters:
      - in: body
        name: JSON
        schema:
          type: object
          properties:
            expenseId:
              type: string
              description: ID of the expense to delete
      responses:
        "200":
          description: OK
          schema:
            type: object
            properties:
              _id:
                type: string
              name:
                type: string
              description:
                type: string
              cost:
                type: number
        "400":
          description: Malformed request or JSON
          schema:
            $ref: '#/responses/BadRequest'
  /expenses/updateExpense:
    post:
      summary: UPDATE expense endpoint
      description: Modify and expense properties
      parameters:
      - in: body
        name: JSON
        schema:
          type: object
          properties:
            expenseId:
              type: string
              description: ID of the expense to modify
            name:
              type: string
            description:
              type: string
            cost:
              type: number
      responses:
        "200":
          description: OK
          schema:
            type: object
            properties:
              expenseId:
                description: Same as input ID
                type: string
        "400":
          description: Malformed request or JSON
          schema:
            $ref: '#/responses/BadRequest'
  /expenses/deleteExpense:
    post:
      summary: DELETE expense endpoint
      description: Remove an expense and associated data
      parameters:
      - in: body
        name: JSON
        schema:
          type: object
          properties:
            expenseId:
              type: string
              description: ID of the expense to delete
      responses:
        "200":
          description: OK
        "400":
          description: Malformed request or JSON
          schema:
            $ref: '#/responses/BadRequest'      
definitions:
    LoginDefinition:
      type: object
      properties:
        email:
          type: string
          description: Authentication username/email
          example: sample@example.com
        password:
          type: string
          description: Authentication password
          example: COP4331
    RegisterDefinition:
      type: object
      properties:
        name:
          type: string
          description: Full name of the user
          example: Rick Leinecker
        email:
          type: string
          description: Authentication email
          example: sample@example.com
        password:
          type: string
          description: Authentication password
          example: COP4331
    UserFullRow:
      type: object
      properties:
        email:
          type: string
          description: The application email
          example: sample@example.com
        name:
          type: string
          description: The application first and last name
          example: John Doe
    ErrorInfo:
      type: object
      properties:
        error:
          type: string
          description: The text description of the error.
          example: Information about the error
responses:
  BadRequest:
    description: Malformed request or JSON on front-end
    schema:
      $ref: '#/definitions/ErrorInfo'
  ServerError:
    description: Unknown error or exception on back-end
    schema:
      $ref: '#/definitions/ErrorInfo'
