swagger: "2.0"

info:
  title: Accountability Expense-Tracker API
  version: 1-oas3
  
host: accountability-190955e8b06f.herokuapp.com
basePath: /api
schemes:
  - https

paths:
  /login:
    post:
      summary: Application user login endpoint
      description: Performs user authentication
      parameters:
      - in: body
        name: Login
        schema:
              $ref: '#/definitions/LoginDefinition'
      responses:
        "200":
          description: Authentication successful
          schema:
              $ref: '#/definitions/UserFullRow'
        "400":
          description: Malformed request or JSON on front-end
          schema:
                $ref: '#/definitions/ErrorInfo'
        "404":
          description: "Authentication failure, either wrong username or password"
          schema:
                $ref: '#/definitions/ErrorInfo'
        "500":
          description: Unknown error or exception on back-end
          schema:
                $ref: '#/definitions/ErrorInfo'
  /registerUser:
    post:
      summary: New user registration endpoint
      description: Creates a new application user
      parameters:
      - in: body
        name: Register
        schema:
          $ref: '#/definitions/RegisterDefinition'
      responses:
        "200":
          description: Registration successful
          schema:
              $ref: '#/definitions/UserFullRow'
        "400":
          description: Malformed request or JSON on front-end
          schema:
              $ref: '#/definitions/ErrorInfo'
        "409":
          description: Email already exists
          schema:
              $ref: '#/definitions/ErrorInfo'
        "500":
          description: Unknown error or exception on back-end
          schema:
              $ref: '#/definitions/ErrorInfo'
definitions:
    LoginDefinition:
      type: object
      properties:
        email:
          type: string
          description: Authentication username/email
          example: sample@example.com
        password:
          type: string
          description: Authentication password
          example: COP4331
    RegisterDefinition:
      type: object
      properties:
        name:
          type: string
          description: Full name of the user
          example: Rick Leinecker
        email:
          type: string
          description: Authentication email
          example: sample@example.com
        password:
          type: string
          description: Authentication password
          example: COP4331
    UserFullRow:
      type: object
      properties:
        email:
          type: string
          description: The application email
          example: sample@example.com
        name:
          type: string
          description: The application first and last name
          example: John Doe
    ErrorInfo:
      type: object
      properties:
        error:
          type: string
          description: The text description of the error.
          example: Information about the error
responses:
  BadRequest:
    description: Malformed request or JSON on front-end
    schema:
      $ref: '#/definitions/ErrorInfo'
  ServerError:
    description: Unknown error or exception on back-end
    schema:
      $ref: '#/definitions/ErrorInfo'
