name: SyncDeploy
run-name: This syncs up the deploy branch with 
on: workflow_dispatch
jobs:
  sync-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git fetch origin deploy:deploy
          git checkout deploy
          git merge --ff-only main
          git push --set-upstream origin deploy
