name: SyncDeploy
run-name: This syncs up the deploy branch with 
on: workflow_dispatch
jobs:
  sync-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: deploy
      - run: |
          git merge --ff-only origin/main
          git push
